# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('chinese', models.CharField(max_length=20)),
                ('math', models.CharField(max_length=20)),
                ('english', models.CharField(max_length=20)),
                ('physics', models.CharField(max_length=20)),
                ('chemistry', models.CharField(max_length=20)),
            ],
        ),
    ]
