# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('chinese', models.IntegerField(default=0)),
                ('math', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('chemistry', models.IntegerField(default=0)),
                ('scoresum', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
